// src/resources/js/services/chat/react/ChatArea.tsx
import React, { useEffect, useState } from "react";

import ChatClient from "../ChatClient";

type Prop = {
    chatClient: ChatClient;
};

/** チャットコンポーネント */
export default function ChatArea({ chatClient }: Prop) {
    const [message, setMessage] = useState("");
    const [messageList, setMessageList] = useState([]);
    const [userList, setUserList] = useState([]);

    useEffect(() => {
        chatClient.addMessage = (row) => {
            setMessageList((list) => [row, ...list]);
        };
        chatClient.setUsers = (users) => {
            console.log('users', users);
            setUserList([...users]);
        }
    }, []);

    const sendMessage = (type, options: any = []) => {
        console.log(message);
        chatClient.sendMessage(message, type, options);
        setMessage("");
    };

    const handleKeyDown = (e) => {
        if (e.key === "Enter") sendMessage("websocket");
    };

    return (
        <div className="max-w-2xl mx-auto py-6">
            <div>
                <input
                    type="text"
                    value={message}
                    className="border p-1 mr-2 w-80"
                    onKeyDown={handleKeyDown}
                    onChange={(e) => setMessage(e.target.value)}
                />
                <button
                    className="p-1 border bg-gray-200 ml-2"
                    onClick={() => sendMessage("websocket")}
                >
                    Send (W)
                </button>
                <button
                    className="p-1 border bg-gray-200 ml-2"
                    onClick={() => sendMessage("redis")}
                >
                    Send (R)
                </button>
                <button
                    className="p-1 border bg-gray-200 ml-2"
                    onClick={() => sendMessage("echo")}
                >
                    Send (E)
                </button>
                <button
                    className="p-1 border bg-gray-200 ml-2"
                    onClick={() => sendMessage("echo", {others: true})}
                >
                    Send (E,O)
                </button>
            </div>

            <div className="border border-gray-700 p-2 mb-2 h-80 mt-5 overflow-y-auto">
                {messageList.map((data, index) => (
                    <p key={index}>
                        {data.data.message}
                        <span className="ml-2 text-sm text-gray-400">
                            by {data.data.name}
                        </span>
                    </p>
                ))}
            </div>

            <div className="mt-5">
                接続ユーザー一覧
                <div className="border-2 border-gray-300 p-2 mb-2 h-40 mt-2 overflow-y-auto">
                    {userList.map((user, index) => (
                        <p key={index}>
                            {user.id} {user.name}
                        </p>
                    ))}
                </div>
            </div>
        </div>
    );
}

// src/resources/js/services/chat-echo/vue/ChatArea.vue
<script lang="ts">
import { defineComponent } from "vue";
import ChatClient from "../ChatClient";
import ChatMessageInput from "./chat-area/ChatMessageInput.vue";

export default defineComponent({
    name: "ChatEchoArea",

    props: {
        chatClient: {
            type: Object as () => ChatClient,
            required: true,
        },
    },

    data() {
        return {
            message: "" as string,
            messageList: [] as any[],
            userList: [] as any[],
        };
    },

    components: {
        ChatMessageInput,
    },

    mounted() {
        // Echoからのメッセージ受信
        this.chatClient.addMessage = (row: any) => {
            this.messageList = [row, ...this.messageList];
        };

        // 接続ユーザー一覧更新
        this.chatClient.setUsers = (users: any[]) => {
            console.log("users", users);
            this.userList = [...users];
        };
    },

    methods: {
        /** メッセージ送信 */
        sendMessage(options: any = []) {
            console.log(this.message);
            this.chatClient.sendMessage(this.message, options);
            this.message = "";
        },

        /** Enterキー送信 */
        handleKeyDown(e: KeyboardEvent) {
            if (e.key === "Enter") {
                this.sendMessage();
            }
        },
    },
});
</script>

<template>
    <div class="max-w-2xl mx-auto py-6">
        <!-- 入力エリア -->
        <div>
            <ChatMessageInput
                v-model:propMessage="message"
                @send="sendMessage"
            />
        </div>

        <!-- メッセージ一覧 -->
        <div class="border border-gray-700 p-2 mb-2 h-80 mt-5 overflow-y-auto">
            <p v-for="(data, index) in messageList" :key="index">
                {{ data.data.message }}
                <span class="ml-2 text-sm text-gray-400">
                    by {{ data.data.name }}
                </span>
            </p>
        </div>

        <!-- 接続ユーザー一覧 -->
        <div class="mt-5">
            接続ユーザー一覧
            <div
                class="border-2 border-gray-300 p-2 mb-2 h-40 mt-2 overflow-y-auto"
            >
                <p v-for="(user, index) in userList" :key="index">
                    {{ user.id }} {{ user.name }}
                </p>
            </div>
        </div>
    </div>
</template>
