// src/resources/js/services/tweet/vue/TweetArea.vue
<script setup lang="ts">
import { ref, onMounted } from "vue";
import TweetForm from "./tweet-area/TweetForm.vue";
import TweetList from "./tweet-area/TweetList.vue";
import type TweetClient from "../TweetClient";
import { setIsLoading } from "@/services/ui/message";
import { TweetContainer } from "../types";

const props = defineProps<{
    initialTweets: any[];
    tweetClient: TweetClient;
}>();

const tweetContainers = ref<TweetContainer[]>([]);
const content = ref("");
const errors = ref<Record<string, any>>({});

/** ツイート一覧から、ツイートコンテナー一覧を作成 */
const makeTweetContainers = (tweets: any[]): TweetContainer[] => {
    return tweets.map((tweet) => ({
        tweet,
        isNew: false,
    }));
};

/* handleSubmit も親で管理 */
const handleSubmit = async (e: Event) => {
    e.preventDefault();

    setIsLoading(true);
    try {
        await props.tweetClient.sendTweet(content.value);

        content.value = "";
        errors.value = {};
    } catch (error: any) {
        if (error.response?.status === 422) {
            errors.value = error.response.data.errors;
        }
    } finally {
        setIsLoading(false);
    }
};

onMounted(() => {
    props.tweetClient.addTweet = (tweet: any) => {
        tweetContainers.value = [
            { tweet, isNew: true },
            ...tweetContainers.value,
        ];
    };

    tweetContainers.value = makeTweetContainers(props.initialTweets);
});
</script>

<template>
    <div>
        <TweetForm
            v-model:content="content"
            :errors="errors"
            @submit="handleSubmit"
        />
        <TweetList :tweetContainers="tweetContainers" />
    </div>
</template>

// src/resources/js/services/tweet/react/TweetArea.tsx
import React, { useEffect, useState } from "react";
import TweetForm from "./tweet-area/TweetForm";
import TweetList from "./tweet-area/TweetList";
import TweetClient from "../TweetClient";
import { setIsLoading } from "@/services/ui/message";

type Prop = {
    initialTweets: any;
    tweetClient: TweetClient;
};

export default function TweetApp({ initialTweets, tweetClient }: Prop) {
    const [tweetContainers, setTweetContainers] = useState([]);
    const [content, setContent] = useState("");
    const [errors, setErrors] = useState({});

    useEffect(() => {
        tweetClient.addTweet = (tweet) => {
            setTweetContainers((list) => [{ tweet, isNew: true }, ...list]);
        };

        setTweetContainers(makeTweetContainers(initialTweets));
    }, []);

    /** ツイート一覧から、ツイートコンテナー一覧を作成 */
    const makeTweetContainers = (tweets) => {
        const list: any = [];
        for (const tweet of tweets) {
            list.push({
                tweet,
                isNew: false,
            });
        }
        return list;
    };

    // handleSubmit も親で管理
    const handleSubmit = async (e) => {
        e.preventDefault();

        setIsLoading(true);
        try {
            await tweetClient.sendTweet(content);

            setContent("");
            setErrors({});
        } catch (error) {
            if (error.response?.status === 422) {
                setErrors(error.response.data.errors);
            }
        }
        setIsLoading(false);
    };

    return (
        <div>
            <TweetForm
                content={content}
                setContent={setContent}
                errors={errors}
                onSubmit={handleSubmit} // フォームの submit は親に任せる
            />
            <TweetList tweetContainers={tweetContainers} />
        </div>
    );
}
