// src/resources/js/services/development/react/test-area-react/UIArea.tsx
import React, { useEffect, useState, useRef } from "react";

import { showToast, setIsLoading } from "@/services/ui/message";

let cnt2 = 0;

/** UI動作確認 */
export default function UIArea() {
    const [cnt, setCnt] = useState(0);
    const refCnt = useRef(0);

    /** ロード画面の動作確認 */
    const loadingTest = () => {
        console.log("Loading");
        setIsLoading(true);
        setTimeout(() => {
            setIsLoading(false);
        }, 2000);
    };

    /** トーストの動作確認 */
    const toastTest = (type) => {
        refCnt.current++;
        setCnt(refCnt.current);
        cnt2++;

        const msg = `トーストテスト type:${type} cnt:${cnt} refCnt:${refCnt.current} cnt2:${cnt2}`;
        console.log(msg);
        showToast(msg, type);
    };

    return (
        <>
            <div className="space-y-2">
                <div>UI動作確認（reactからvueを動かす）</div>

                <div>
                    <button
                        className="app-btn-secondary mr-2"
                        onClick={loadingTest}
                    >
                        Loading
                    </button>
                </div>

                <div>
                    <button
                        className="app-btn-primary mr-2"
                        onClick={() => toastTest("notice")}
                    >
                        Toast notice
                    </button>
                    <button
                        className="app-btn-primary mr-2"
                        onClick={() => toastTest("alert")}
                    >
                        Toast alert
                    </button>
                    <button
                        className="app-btn-primary mr-2"
                        onClick={() => {
                            toastTest("notice");
                            toastTest("alert");
                        }}
                    >
                        Toast 2
                    </button>
                    cnt: {cnt}
                </div>
            </div>
        </>
    );
}

// src/resources/js/services/development/vue/test-area-vue/UIArea.vue
<script setup lang="ts">
/** UI動作確認 */

import { ref } from "vue";

import { showToast, setIsLoading } from "@/services/ui/message";

const cnt = ref<number>(0);

/** ロード画面の動作確認 */
const loadingTest = () => {
    console.log("Loading vue.js");
    setIsLoading(true);
    setTimeout(() => {
        setIsLoading(false);
    }, 2000);
};

/** トーストの動作確認 */
const toastTest = (type) => {
    cnt.value++;
    const msg = `トーストテスト vue.js type:${type} cnt.value:${cnt.value}`;
    console.log(msg);
    showToast(msg, type);
};
</script>

<template>
    <div>
        UI動作確認

        <div class="mt-5">
            <button class="app-btn-secondary mr-2" @click="loadingTest">
                Loading
            </button>
        </div>

        <div class="mt-5 space-x-2">
            <button class="app-btn-primary" @click="() => toastTest('notice')">
                Toast notice
            </button>
            <button class="app-btn-primary" @click="() => toastTest('alert')">
                Toast alert
            </button>
            <button
                class="app-btn-primary"
                @click="
                    () => {
                        toastTest('notice');
                        toastTest('alert');
                    }
                "
            >
                Toast 2
            </button>
            <span>cnt: {{ cnt }}</span>
        </div>
    </div>
</template>
