// src/resources/js/services/tweet/vue/tweet-area/TweetForm.vue
<script setup lang="ts">
import { Errors } from "@/services/form/types";

const content = defineModel<string>("content", {
    required: true,
});

defineProps<{
    errors: Errors;
}>();

defineEmits<{
    (e: "submit", event: Event): void;
}>();
</script>

<template>
    <form @submit="$emit('submit', $event)" class="mb-4">
        <textarea
            v-model="content"
            rows="3"
            class="w-full border rounded p-2"
            placeholder="What's happening?"
        />

        <p v-if="errors.content" class="app-error-text">
            {{ errors.content[0] }}
        </p>

        <button type="submit" class="mt-2 app-btn-primary">Tweet</button>
    </form>
</template>

// src/resources/js/services/tweet/react/tweet-area/TweetForm.tsx
import React from "react";

export default function TweetForm({ content, setContent, errors, onSubmit }) {
    return (
        <form onSubmit={onSubmit} className="mb-4">
            <textarea
                rows={3}
                className="w-full border rounded p-2"
                placeholder="What's happening?"
                value={content}
                onChange={(e) => setContent(e.target.value)}
            />
            {errors.content && (
                <p className="app-error-text">{errors.content[0]}</p>
            )}
            <button type="submit" className="mt-2 app-btn-primary">
                Tweet
            </button>
        </form>
    );
}
