// src/resources/js/services/tweet/vue/tweet-area/TweetList.vue
<script setup lang="ts">
import { TweetContainer } from "../../types";

defineProps<{
    tweetContainers: TweetContainer[];
}>();
</script>

<template>
    <div class="space-y-4">
        <div
            v-for="tweetContainer in tweetContainers"
            :key="tweetContainer.tweet.id"
            class="border rounded p-4"
        >
            <p v-if="tweetContainer.isNew" class="text-blue-500">new</p>

            <p class="text-gray-800">
                {{ tweetContainer.tweet.content }}
            </p>

            <p class="text-gray-500 text-sm">
                by {{ tweetContainer.tweet.user.name }} -
                {{ new Date(tweetContainer.tweet.created_at).toLocaleString() }}
            </p>
        </div>
    </div>
</template>

// src/resources/js/services/tweet/tweet-app/TweetList.tsx
import React from 'react';

export default function TweetList({ tweets }) {
    return (
        <div className="space-y-4">
            {tweets.map(tweet => (
                <div key={tweet.id} className="border rounded p-4">
                    <p className="text-gray-800">{tweet.content}</p>
                    <p className="text-gray-500 text-sm">
                        by {tweet.user.name} - {new Date(tweet.created_at).toLocaleString()}
                    </p>
                </div>
            ))}
        </div>
    );
}
