// src/resources/js/services/ui/vue/message/ProgressBar.vue
<template>
    <div class="w-72 space-y-1">
        <!-- プログレスバー -->
        <div class="w-full h-3 bg-gray-200 rounded-full overflow-hidden">
            <div
                class="h-full bg-green-500 transition-all duration-300"
                :style="{ width: clamped + '%' }"
            />
        </div>

        <!-- 数値表示 -->
        <p class="text-gray-700 font-medium">{{ clamped }}%</p>
    </div>
</template>

<script setup lang="ts">
/** プログレスバーコンポーネント */

import { computed } from "vue";
import { clamp } from "@/services/data/number";

const props = defineProps<{
    progress: number;
}>();

const clamped = computed(() => clamp(Math.floor(props.progress), 0, 100));
</script>

// src/resources/js/services/ui/react/message/ProgressBar.tsx
import { useState } from "react";

import { clamp } from "@/services/data/number";

type Prop = {
    progress: number;
};

/** プログレスバーコンポーネント */
export default function ProgressBar({ progress }: Prop) {
    const clamped = clamp(Math.floor(progress), 0, 100);

    return (
        <div className="w-72 space-y-1">
            {/* プログレスバー */}
            <div className="w-full h-3 bg-gray-200 rounded-full overflow-hidden">
                <div
                    className="h-full bg-green-500 transition-all duration-300"
                    style={{ width: `${clamped}%` }}
                />
            </div>

            {/* 数値表示 */}
            <p className="text-gray-700 font-medium">{clamped}%</p>
        </div>
    );
}
